version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: kc
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 5431:8080
