version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: kc
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 5431:8080
