version: '3.1'

# run
# docker stack deploy -c stack.yml mysql

services:
  db:
    image: mysql:5
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: keep_coming
    ports:
      - 3306:3306

  adminer:
    image: adminer
    ports:
      - 8989:8080
